imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        path: '%database_path%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    port: '%mailer_port%'
    encryption: '%mailer_encryption%'
    spool: { type: memory }

# Asset configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
            bootstrap_js:
                inputs:
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.bundle.min.js"
                output: "js/bootstrap_js.js"
            bootstrap_css:
                inputs:
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.min.css"
                output: "css/bootstrap_css.css"
                filters: [cssrewrite]

            font_awesome_css:
                inputs:
                    - "%kernel.root_dir%/../vendor/components/font-awesome/css/font-awesome.min.css"
                output: "css/fon-awesome_css.css"
                filters: [cssrewrite]
            font_awesome_webfont_ttf:
                inputs:
                    - "%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.ttf"
                output: "fonts/fontawesome-webfont.ttf"
            font_awesome_webfont_woff:
                inputs:
                    - "%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff"
                output: "fonts/fontawesome-webfont.woff"
            font_awesome_webfont_woff2:
                inputs:
                    - "%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff2"
                output: "fonts/fontawesome-webfont.woff2"

            jquery:
                inputs:
                    - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"
                output: "js/jquery.js"

